Tracker:AddLocations("locations/7Zee.json")
Tracker:AddLocations("locations/Ancient Ruins.json")
Tracker:AddLocations("locations/Ancient Ruins Transition.json")
Tracker:AddLocations("locations/Ash Isle Vault.json")
Tracker:AddLocations("locations/Ash Isles.json")
Tracker:AddLocations("locations/Personal Upgrades.json")
Tracker:AddLocations("locations/Dry Reef.json")
Tracker:AddLocations("locations/Glass Desert.json")
Tracker:AddLocations("locations/Indigo Quarry.json")
Tracker:AddLocations("locations/Moss Blanket.json")
Tracker:AddLocations("locations/Moss Blanket Vault.json")
Tracker:AddLocations("locations/Nimble Valley.json")
Tracker:AddLocations("locations/Ogdens Retreat.json")
Tracker:AddLocations("locations/Ring Island.json")
Tracker:AddLocations("locations/Ring Island Vault.json")
Tracker:AddLocations("locations/Plortsanity.json")
Tracker:AddLocations("locations/Slime Gate.json")
Tracker:AddLocations("locations/The Docks.json")
Tracker:AddLocations("locations/The Grotto.json")
Tracker:AddLocations("locations/The Lab.json")
Tracker:AddLocations("locations/The Mustache Shrine.json")
Tracker:AddLocations("locations/The Overgrowth.json")
Tracker:AddLocations("locations/The Slime Sea.json")
Tracker:AddLocations("locations/The Slimeulation.json")
Tracker:AddLocations("locations/The Wilds.json")